// Code generated by goctl. DO NOT EDIT.
package types

type OssReq struct {
	TenantResult
	Category   int `json:"category"`   // 所属分类
	OssCode    int `json:"ossCode"`    // 资源编号
	Endpoint   int `json:"endpoint"`   // 资源地址
	AccessKey  int `json:"accessKey"`  // accessKey
	SecretKey  int `json:"secretKey"`  // secretKey
	BucketName int `json:"bucketName"` // 空间名
	AppId      int `json:"appId"`      // 应用ID TencentCOS需要
	Region     int `json:"region"`     // 地域简称 TencentCOS需要
	Remark     int `json:"remark"`     // 所属分类
}

type OssListReq struct {
	PageInfo
}

type MakeBucketReq struct {
	BucketName string `json:"bucketName"` // 存储桶名称
}

type EmptyResult struct {
}

type BaseResult struct {
	Id uint `json:"id"` // 主键ID
}

type TenantResult struct {
	BaseResult
	TenantId uint `json:"tenantId"` // 租户ID
}

type PageInfo struct {
	Page     int `json:"page,range=[1:100],default=1"`     // 页码
	PageSize int `json:"pageSize,range=[1:100],default=1"` // 每页大小
}

type PageResult struct {
	List     interface{} `json:"list"`
	Total    int64       `json:"total"`
	Page     int         `json:"page"`     // 页码
	PageSize int         `json:"pageSize"` // 每页大小
}
