// Code generated by goctl. DO NOT EDIT.
package types

type Oss struct {
	Category string `json:"category"` // 所属分类
}

type OssListReq struct {
	PageInfo
	Oss
}

type MakeBucketReq struct {
	BucketName string `json:"bucketName"` // 存储桶名称
}

type EmptyReply struct {
}

type PageInfo struct {
	Page     int `json:"page,range=[1:100],default=1"`     // 页码
	PageSize int `json:"pageSize,range=[1:100],default=1"` // 每页大小
}

type PageResult struct {
	List     interface{} `json:"list"`
	Total    int64       `json:"total"`
	Page     int         `json:"page"`     // 页码
	PageSize int         `json:"pageSize"` // 每页大小
}
