// Code generated by goctl. DO NOT EDIT.
// Source: push.proto

package push

import (
	"context"

	"github.com/hehanpeng/go-zero-resource/push/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty               = pb.Empty
	PingResp            = pb.PingResp
	PushOneMsgToUserReq = pb.PushOneMsgToUserReq
	PushOneMsgToUserRes = pb.PushOneMsgToUserRes

	Push interface {
		Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResp, error)
		PushOneWsMsgToUser(ctx context.Context, in *PushOneMsgToUserReq, opts ...grpc.CallOption) (*PushOneMsgToUserRes, error)
	}

	defaultPush struct {
		cli zrpc.Client
	}
)

func NewPush(cli zrpc.Client) Push {
	return &defaultPush{
		cli: cli,
	}
}

func (m *defaultPush) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResp, error) {
	client := pb.NewPushClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultPush) PushOneWsMsgToUser(ctx context.Context, in *PushOneMsgToUserReq, opts ...grpc.CallOption) (*PushOneMsgToUserRes, error) {
	client := pb.NewPushClient(m.cli.Conn())
	return client.PushOneWsMsgToUser(ctx, in, opts...)
}
