// Code generated by goctl. DO NOT EDIT.
package types

type PingReply struct {
	Msg string `json:"msg"`
}

type EmptyReply struct {
}

type BaseReq struct {
	Id int64 `json:"id"` // 主键ID
}

type TenantReq struct {
	Id       int64  `json:"id"`       // 主键ID
	TenantId string `json:"tenantId"` // 租户ID
}

type RegisterReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}

type KqSendReq struct {
	Msg string `json:"msg"` // 消息
}
