// Code generated by goctl. DO NOT EDIT!
// Source: message.proto

package server

import (
	"context"

	"github.com/hehanpeng/go-zero-resource/message/internal/logic"
	"github.com/hehanpeng/go-zero-resource/message/internal/svc"
	"github.com/hehanpeng/go-zero-resource/message/pb"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServer) Ping(ctx context.Context, in *pb.Empty) (*pb.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *MessageServer) KqSend(ctx context.Context, in *pb.KqSendReq) (*pb.Empty, error) {
	l := logic.NewKqSendLogic(ctx, s.svcCtx)
	return l.KqSend(in)
}
