// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-zero-resource/service/oss-endpoint/cmd/api/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/make-bucket",
				Handler: makeBucketHandler(serverCtx),
			},
		},
	)
}
