// Code generated by goctl. DO NOT EDIT.
// Source: push.proto

package server

import (
	"context"

	"github.com/hehanpeng/go-zero-resource/push/internal/logic"
	"github.com/hehanpeng/go-zero-resource/push/internal/svc"
	"github.com/hehanpeng/go-zero-resource/push/pb"
)

type GtwServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGtwServer
}

func NewGtwServer(svcCtx *svc.ServiceContext) *GtwServer {
	return &GtwServer{
		svcCtx: svcCtx,
	}
}

func (s *GtwServer) Ping(ctx context.Context, in *pb.Empty) (*pb.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *GtwServer) PushOneMsgToUser(ctx context.Context, in *pb.PushOneMsgToUserReq) (*pb.PushOneMsgToUserRes, error) {
	l := logic.NewPushOneMsgToUserLogic(ctx, s.svcCtx)
	return l.PushOneMsgToUser(in)
}
