// Code generated by goctl. DO NOT EDIT!
// Source: messsage.proto

package message

import (
	"context"

	"gtw/message/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty    = pb.Empty
	PingResp = pb.PingResp

	Message interface {
		Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResp, error)
	}

	defaultMessage struct {
		cli zrpc.Client
	}
)

func NewMessage(cli zrpc.Client) Message {
	return &defaultMessage{
		cli: cli,
	}
}

func (m *defaultMessage) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResp, error) {
	client := pb.NewMessageClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
