// Code generated by goctl. DO NOT EDIT.
// Source: mgtw.proto

package mgtw

import (
	"context"

	"github.com/hehanpeng/go-zero-resource/mgtw/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty               = pb.Empty
	PingResp            = pb.PingResp
	PushOneMsgToUserReq = pb.PushOneMsgToUserReq
	PushOneMsgToUserRes = pb.PushOneMsgToUserRes

	Mgtw interface {
		Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResp, error)
		PushOneWsMsgToUser(ctx context.Context, in *PushOneMsgToUserReq, opts ...grpc.CallOption) (*PushOneMsgToUserRes, error)
	}

	defaultMgtw struct {
		cli zrpc.Client
	}
)

func NewMgtw(cli zrpc.Client) Mgtw {
	return &defaultMgtw{
		cli: cli,
	}
}

func (m *defaultMgtw) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResp, error) {
	client := pb.NewMgtwClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultMgtw) PushOneWsMsgToUser(ctx context.Context, in *PushOneMsgToUserReq, opts ...grpc.CallOption) (*PushOneMsgToUserRes, error) {
	client := pb.NewMgtwClient(m.cli.Conn())
	return client.PushOneWsMsgToUser(ctx, in, opts...)
}
