// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go-zero-resource/service/resource/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(engine *rest.Server, serverCtx *svc.ServiceContext) {
	engine.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/oss/detail",
				Handler: ossDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oss/list",
				Handler: ossListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oss/create",
				Handler: createOssHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oss/update",
				Handler: updateOssHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oss/delete",
				Handler: deleteOssHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oss/endpoint/make-bucket",
				Handler: makeBucketHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oss/endpoint/remove-bucket",
				Handler: removeBucketHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oss/endpoint/stat-file",
				Handler: statFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oss/endpoint/put-file",
				Handler: putFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oss/endpoint/get-file",
				Handler: getFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oss/endpoint/remove-file",
				Handler: removeFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/oss/endpoint/remove-files",
				Handler: removeFilesHandler(serverCtx),
			},
		},
	)
}
