// Code generated by goctl. DO NOT EDIT.
// Source: mgtw.proto

package server

import (
	"context"

	"github.com/hehanpeng/go-zero-resource/mgtw/internal/logic"
	"github.com/hehanpeng/go-zero-resource/mgtw/internal/svc"
	"github.com/hehanpeng/go-zero-resource/mgtw/pb"
)

type MgtwServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMgtwServer
}

func NewMgtwServer(svcCtx *svc.ServiceContext) *MgtwServer {
	return &MgtwServer{
		svcCtx: svcCtx,
	}
}

func (s *MgtwServer) Ping(ctx context.Context, in *pb.Empty) (*pb.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *MgtwServer) PushOneWsMsgToUser(ctx context.Context, in *pb.PushOneMsgToUserReq) (*pb.PushOneMsgToUserRes, error) {
	l := logic.NewPushOneWsMsgToUserLogic(ctx, s.svcCtx)
	return l.PushOneWsMsgToUser(in)
}
